# Use the official Redis image as the base image
FROM redis:alpine

# Expose the port 6399
EXPOSE 6399

# Command to start Redis with the port set by the environment variable
CMD ["redis-server","--port","6399"]

